language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsrubia
  api_key:
    secure: JlxFhR57iClx/avsswPLT6zduTpm4tNHcmTmJaedJEIe4vp82wRP17qHJmLPULQCzXwA5ifKPcu7j0pxkF/TDchgG1jPCfL77jDfvHLIDSQkU+5hwj7GVWuPdx/ImVuu48gqxhx+20cl99nSOInpMo+WKriOVHOfP7odnfo5XHj9LD2ayzMZV79bTvXsYCwv2QgL9+7zt49gyYYEbfUM6GruRKDXi3L/VZYuAIL+v5h81VZFo2d3D3j4pg9VgZAWxpcXNLV8TWfbxek20Tjipsw4811lmqQ+gfO7wsnTZoVKBuYfi3PYLMJ9Gz4stqHMY9+sB3TBde5AvPyKCpTbD58C75ydyd/Zv5WRrEYjdVDhB6eVtC7LZj2aD7uOL0kRkQRVFW/w6CuFYN2xMpGlStt4ziN8laydcQWyVCfj+T0nMbf5ffOSvmO60A9VCsu3Etri1Hz/jTlY/KRG4Vnmcg8PZwLQ7oQIJHvRZzFQDLxVx90bbieYIk+oA6GDSIdIy62ssPjE1T17BibXBwwzn6vTxscazsommk/ChKPldWIPR9qB/7qV7tb5sIOHZ/DPGhmobsybODdUbI56oZtBKMM09bCRAmiZSx4qKQvPRAvKYLQh8P4TnTUFK31l0qC2nShdgC1uFJa1v9OWVqHEf1HRNrcmtnHlRQSQvd6pv+s=
