language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4labsrubia
  api_key:
    secure: Xa60lQn9U6a+L8DYyLoSmmuy03bxL/FRtKlLcg6Zh9JNS7Pt+My1Tc/OKcI4RO1vOIxbFsdYja++dXdgXwatqsQvZ21RQ5tpSEe9Gmz5RLXHGWsmO7X9APdn2O6fchvGVuGHA6LAlbb/Z4RjvL6mrY7QSFm73Xr+RynJ5aYxD0thxKBJWATwavadco/kZQGnXpURtzQ5N36uCrevFef3qaN+/4SXKz2xIfDOwQr8HSCOFd6sB4QNOGbrUOz0SVEE1Cym13rHvk4NVNS3v7Lm0VWlYRRVDV2qLWocNREaknbF3Pma5jsrtxJu6tI+QyJ/xGNz34HeYhCt+hxwDxENKJ/M9iVpiddQmoXQKuAq0i0ZIqwuM0ULO1+1iqCwP+FEA+oQfGQQ9Pd5Qck5r1ro/tMBS0aC24Rrtq4RjXFt9YWxpiwsnxteUAO4sA8XH98NVXVKz2Up8oy5wC7ya2RQSI/Lt95B1AYxLdWXhI1VssT47KvXyccKBnUpXy59YQ+IUYP+lR7jpd8ykZxu7+QgZuPIfZaVqHSXMyWol9riBY2GX7CrMwM5suUyaU1lXc95Q4sJRIUUxcYJUgNyq8Hq+OAIc9UNDZ70zdduBqVZQ4OoPFnHyMdhsmhsmI/+2cvINr5K0BLBVjM7dtrnha1fMIKGwWri4K32S8MOB8htLNE=
