language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsrubia
  api_key:
    secure: T70/WOp6l1zNvJoxkqP83YoBrTszlCIhAOSSGGwHEoZCLzrVj02odGQiPVqNTaJVo0HWpUt/oEsbDYVko2y0d/+8G/Qakig3K7FiTQ6Ge01oAAfVBKSTjJ4IBpSmAMCBIWhG+ENw/1Z/p4JHWpVaPX2YTokTziSuUAC8csI976ZR90bLaF8My+p62MZegcXufdIG9pLgoRsGh2z9uy+Pw9VvcA6L8641vW0TpkCYzNjYI2k1JvKW0VymplvleZaBkwjjOM96aEaFtE4LmEw2ZZvEUgk47BPtSqfw0yBDe/F6n3QZI32XwkEegHriDRKvAONHn/EsPIis3+KntNQbuVFuRpDBp6I7qeQhhR3yOWVJNKf6dxlNHVasihS7AhzWJaCKZTbaqXGQWSmpQtyxmrW42IeUdlKa37HpmXLr7qaQZyjFzdenk+5ITcoJyFXiCPu/lsYF9z2sF3HwGM8n2l7yohNYWGMWfpzcALCD9j2UGYrZuanFIz0VZVADnQbN/JK0MtfUyiLQKNh6sb4uVSxbqZbajxx5bSLA0r5HyKesDjbXo7adySzTAbtZGKSEHC9Rgf20UVxi9K5UqzznvYTdeCqaE8s/CsmIQn4Casv6wQ0x0wi86rb7eV+7YELkJQtdgGP1w0BM2w0oxKmcP3PQm3Eam5+ICP+lXER6Wds=
