language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsrubia
  api_key:
    secure: ZJkocn1nPACy9GJ4SdEYv/820ophRbPmCwGKCv9tCGD/TFN1CUYOzKO9nA9VxHgTIgJpfByLo6adDliC88AxFAE1onmSK9Mppt2uukhcf2NbOWwZWyl5Jq80JZPpO9BOsnVAoPfmZH0b2swJsubsG4mwiHj2empelwz3lEe3HJ/ar/pZvUy29x6hTGWtDLEcQ3RK//9+SQ7xx5wJ+M2T9/gdzZRHUoqw3l/dY+qEETb6qQHu6LuwoGYtsRCAbrrUZc19A8kPZ3bziWF5bDqaGwglzmmIFQfC7JgHEOsbMHUl3AwX5bkwZSmHkG7CGU/ntFU3/y7kv91wlunHAnUy5eDuqAuS536l+4vlfPWFu7tIj0yWS0DUqTBfWhbU6ZYoqYQyeu9Gv08svPX9qbxsWQvykPmsn8GqeDxaoj2c0QXiQTx9YLE922PI2TSQJGwahjJNZ468B0ffFkCqgg/it8aaJ9FGMFkC+FlkmS3GoKBPhn2Rnr0wMr95UDH96bJ/99tCXtG+WvUHkvObtwn66M6Lx6MDHqS1lVZO16PRGYAPD+jzwL7q3J2hLS/jC948h4Rj5GZEnEHujUKJCtRsDV68NhDwNrFiwF4/SEJAnmP4X/dqkLqN2O0ZE/ISboc4BRhVE86DQoA0oDnOxb6XWfXafVD7cUKFjMVnpzHS5CQ=
